spring:
  data:
    mongodb:
      uri: mongodb://localhost/theincredibles-assignment-jpa
  datasource:
    url: jdbc:mysql://localhost/theincredibles-assignment-jpa?useSSL=false
    username: root
    password: secret
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
